name: Pre-release

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: dist/*
          prerelease: true
          generate_release_notes: true
          automatic_release_tag: bleeding-edge
          repo_token: ${{ secrets.GITHUB_TOKEN }}
