name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: dist/*
          prerelease: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
