name: 'tagged-release'

on:
  push:
    tags:
      - v*

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          prerelease: false
          generate_release_notes: true

      - name: Deploy to Test PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
